config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'user/sessions#new', as: "login"
  delete 'logout', to: 'user/sessions#destroy', as: "logout"

  namespace :user do
    namespace :account do
      resource :password_reset # reset password for account when not logged in
      resource :password # update password for account while logged in
      resource :email_confirmation # confirmation email to confirm user account
    end
    resource :sessions
    resource :registration # user registration
  end
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true
  normalizes :email, with: ->email { email.strip.downcase }

  # tokens that dont have to be stored in the db, one time use we can use generates_token_for
  # inside block we confirm if old password matches with the password_salt. if it doesnt,
  # the user cant sucessfully reset the password and this token will no longer exists.
  generates_token_for :password_reset, expires_in: 15.minutes do
    password_salt&.last(10)
  end

  # inside block we confirm if its the user's email
  generates_token_for :email_confirmation, expires_in: 24.hours do
    email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def authenticate_user!
    redirect_to root_path, alert: "You must be logged in to do that." unless user_signed_in?
  end

  def current_user
    Current.user ||= authenticate_user_from_session
  end
  helper_method :current_user

  def user_signed_in?
    current_user.present?
  end
  helper_method :user_signed_in?

  def authenticate_user_from_session
    User.find_by(id: session[:user_id])
  end

  def login(user)
    Current.user = user
    reset_session
    session[:user_id] = user.id
  end

  def logout(user)
    Current.user = nil
    reset_session
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/user/account/email_confirmations_controller.rb
class User::Account::EmailConfirmationsController < ApplicationController
  before_action :set_user_by_token, only: [:show]

  def show
    @user.update!(confirm: true)
    redirect_to root_path, notice: "Your account has been confirmed!"
  end

  private

  def set_user_by_token
    @user = User.find_by_token_for(:email_confirmation, params[:token])
    redirect_to root_path alert: "That account could not be confirmed." unless @user.present?
  end
end

app/controllers/user/account/password_resets_controller.rb
class User::Account::PasswordResetsController < ApplicationController
  before_action :set_user_by_token, only: [:edit, :update]
  def new # request password reset
  end

  def create # create password reset
    if (user = User.find_by(email: params[:email]))
      PasswordMailer.with(user: user, token: user.generate_token_for(:password_reset)).password_reset.deliver_later
    end

    redirect_to root_path, notice: "Check your email to reset your password"
  end

  def edit
  end

  def update
    if @user.update!(password_params)
      redirect_to login_path, notice: "Your password has been reset succesfully, please log in."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def set_user_by_token
    @user = User.find_by_token_for(:password_reset, params[:token])
    redirect_to new_user_account_password_reset_path alert: "Invalid token, please try again." unless @user.present?
  end
end

app/controllers/user/account/passwords_controller.rb
class User::Account::PasswordsController < ApplicationController
  before_action :authenticate_user!

  def edit
  end

  def update
    if current_user.update!(password_params)
      redirect_to edit_user_account_password_path, notice: "Your password has been updated succesfully"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def password_params
    params.require(:user).permit(
      :password,
      :password_confirmation,
      :password_challenge
    ).with_defaults(password_challenge: "")
  end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(registration_params)
    if @user.save
      login @user

      UserMailer.with(
        user: @user,
        token: @user.generate_token_for(:email_confirmation),
      ).email_confirmation.deliver_later

      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def registration_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < ApplicationController
  def new
  end

  def create
    if user = User.authenticate_by(email: params[:email], password: params[:password])
      login user
      redirect_to root_path, notice: "You have signed in successfully"
    else
      flash[:alert] = "Invalid email or password"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout current_user
    redirect_to root_path, notice: "You have been logged out"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthenticationFromScratch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div style="color: orange"><%= notice %></div>
    <div style="color: red"><%= alert %></div>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<h1>homepage</h1>
<% if user_signed_in? %>
	account confirmed: <%= current_user.confirm? %>
<% end %>

app/views/shared/_navbar.html.erb
<nav>
	<% if user_signed_in? %>
	  <%= link_to "Edit Password", edit_user_account_password_path %>
	  <%= button_to "Log out", user_sessions_path, method: :delete %>
	<% else %>
	  <%= link_to "Sign Up", new_user_registration_path %>
	  <%= link_to "Log in", login_path %>
	<% end %>
</nav>

<style>
	nav {
		display: flex;
		align-items: center;
		justify-content: flex-end;
		padding-bottom: 10px;
		border-bottom: 1px solid;
	}

	nav a {
		margin-right: 10px;
	}
</style>

app/views/user/account/email_confirmations/show.html.erb
confirming your account...

app/views/user/account/password_resets/edit.html.erb
<h1>reset your password</h1>

<%= form_with model: @user, url: user_account_password_reset_path(token: params[:token]) do |form| %>
	<% if form.object.errors.any? %>
		<% form.object.errors.full_messages.each do |message| %>
			<div style="color: red"><%= message %></div>
		<% end %>
	<% end %>

	<div>
		<%= form.label :password, "New Password" %>
		<%= form.password_field :password %>
	</div>

	<div>
		<%= form.label :password_confirmation %>
		<%= form.password_field :password_confirmation %>
	</div>

	<div>
		<%= form.submit "Reset your password" %>
	</div>
<% end %>

app/views/user/account/password_resets/new.html.erb
<h1>reset your password</h1>

<%= form_with model: @user, url: user_account_password_reset_path do |form| %>
	<div>
		<%= form.label :email %>
		<%= form.email_field :email %>
	</div>

	<div>
		<%= form.submit "Reset password" %>
	</div>
<% end %>